# Generated by Django 5.1.3 on 2024-11-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_tipresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipresource',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
