# Generated by Django 5.1.3 on 2024-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_tipresource_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team member.', max_length=200)),
                ('role', models.CharField(help_text='Role of the team member, e.g., CEO, Marketing Head.', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short bio or description of the team member.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the team member.', null=True, upload_to='team_members/')),
                ('joined_date', models.DateField(blank=True, help_text='Date the team member joined.', null=True)),
                ('active', models.BooleanField(default=True, help_text='Mark as active to display on the website.')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-joined_date'],
            },
        ),
    ]
