# Generated by Django 5.1.3 on 2024-12-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Enter the offer message to display on the header.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to activate or deactivate this offer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
